CREATE TABLE COURSE (
 CODE CHAR(10) NOT NULL PRIMARY KEY,
 TITLE VARCHAR(10) NOT NULL
);


CREATE TABLE LOCATION (
 ID INT NOT NULL PRIMARY KEY,
 CITY VARCHAR(10) NOT NULL
);


CREATE TABLE COURSE_SESSION (
 ID INT NOT NULL PRIMARY KEY,
 START_DATE DATE NOT NULL,
 END_DATE DATE NOT NULL,
 COURSE_CODE CHAR(10) NOT NULL,
 LOCATION_ID INT NOT NULL,

 FOREIGN KEY (COURSE_CODE) REFERENCES COURSE (CODE),
 FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION (ID)
);


CREATE TABLE CLIENT (
 ID INT NOT NULL PRIMARY KEY,
 LASTNAME VARCHAR(10) NOT NULL,
 FIRSTNAME VARCHAR(10) NOT NULL,
 ADDRESS VARCHAR(10) NOT NULL,
 PHONE VARCHAR(10) NOT NULL,
 EMAIL VARCHAR(10),
 COURSE_SESSION_ID INT NOT NULL,

 FOREIGN KEY (COURSE_SESSION_ID) REFERENCES COURSE_SESSION (ID)
);
